Added GeoLocation Feature
zeezeee96/weather-app pull request #6
Opened 2021-03-15 14:53 UTC by zeezeee96

~Added Geolocation button for accessing location of user.
~Location Click navigates to weatherdetails page.

2021-03-16 22:16 UTC, Monfernape requested changes

2021-03-16 22:16 UTC, Monfernape commented on package.json
> +  "devDependencies": {
I am not sure if they should be here. You see devDependencies exist for development purpose and when application goes live, they are not loaded. And I think you need these icons for your application.

2021-03-16 22:16 UTC, Monfernape commented on src/components/Searchbar.js
> +  const [geoLocationInfo, setGeoLocationInfo] = useState([])
How about renaming it as location? getGeolocation sounds like a method.

2021-03-16 22:16 UTC, Monfernape commented on src/services/request-service.js
> +  console.log(longitude, latitude)
Cleanup required here. Also, remove consoles across the application

2021-03-21 15:02 UTC, zeezeee96 commented on src/services/request-service.js
> +  console.log(longitude, latitude)
updated

2021-03-21 15:02 UTC, zeezeee96 commented on src/components/Searchbar.js
> +  const [geoLocationInfo, setGeoLocationInfo] = useState([])
done

2021-03-21 19:27 UTC, Monfernape approved these changes

2021-03-21 19:27 UTC, merged